#! /usr/bin/env bash

set -euo pipefail

TEMP=$(getopt -o 'a:,u:' -- "$@")

if [ $? -ne 0 ]; then
	echo 'Terminating...' >&2
	exit 1
fi

# Note the quotes around "$TEMP": they are essential!
eval set -- "$TEMP"
unset TEMP

_AWS_ACCOUNT=""
_IAM_USER=""
while true; do
    case "$1" in
        "-a")
            _AWS_ACCOUNT=$2
            shift 2
            continue
            ;;
        "-u")
            _IAM_USER=$2
            shift 2
            continue
            ;;
        "--")
            shift
            break
            ;;
        *)
            echo "Invalid argument while processing options." >&2
            exit
            ;;
    esac
done

[ -z $_AWS_ACCOUNT ] && echo "Wrong usage!" && exit
[ -z $_IAM_USER ] && echo "Wrong usage!" && exit

p="AWSCredentials/${_AWS_ACCOUNT}/${_IAM_USER}"

cat <<EOF
{
   "Version": 1,
   "AccessKeyId": "$(pass "${p}/ID")",
   "SecretAccessKey": "$(pass "${p}/Key")"
}
EOF
